# The "pi" aspect: pi, the terminal coding agent (https://pi.dev).
#
# The package is vendored from nixpkgs (pkgs/by-name/pi/pi-coding-agent) at a
# newer release than the pinned nixos-26.05 channel ships, because pi moves
# fast and the channel version lags far behind. To bump: set `version` and
# copy the matching `hash`, `npmDepsHash` and `modelData.hash` from
# nixos-unstable's pkgs/by-name/pi/pi-coding-agent/package.nix (or compute
# them with `nix-prefetch` / `prefetch-npm-deps`).
{
  flake.modules.homeManager.pi =
    { pkgs, ... }:
    let
      # The pi package expression, vendored from nixpkgs (see header comment).
      # Instantiated below with the host's pkgs via callPackage.
      piPackage =
        {
          lib,
          buildNpmPackage,
          fetchFromGitHub,
          fetchurl,
          makeBinaryWrapper,
          ripgrep,
          fd,
          stdenvNoCC,
          writableTmpDirAsHomeHook,
          versionCheckHook,
        }:
        buildNpmPackage (finalAttrs: {
          pname = "pi-coding-agent";
          version = "0.86.1";

          src = fetchFromGitHub {
            owner = "earendil-works";
            repo = "pi";
            tag = "v${finalAttrs.version}";
            hash = "sha256-/7+VoRfXdeOwtiNXQYOKg5OHeKuNLIHfODGDNBhWop0=";
          };

          npmDepsHash = "sha256-VxjYw4lN/w0sDboihHAKEhdJFzJa09qZo7vavkTkBuw=";

          # The provider model catalog (packages/ai/src/providers/data/) is
          # generated by a network fetch (models.dev plus provider APIs) and
          # is gitignored upstream, so it is absent from the source tarball.
          # Restore it from the matching published @earendil-works/pi-ai npm
          # package, which ships the hydrated catalog under
          # dist/providers/data/. Bump this hash alongside version.
          modelData = fetchurl {
            url = "https://registry.npmjs.org/@earendil-works/pi-ai/-/pi-ai-${finalAttrs.version}.tgz";
            hash = "sha256-88Nb88YGsJ9iupLSx8ieY+DKGAdUcBAtVWVoTFJLfv0=";
          };

          preConfigure = ''
            mkdir -p packages/ai/src/providers/data
            tar --extract --gzip --file=${finalAttrs.modelData} \
              --directory=packages/ai/src/providers/data \
              --strip-components=4 \
              package/dist/providers/data
          '';

          npmWorkspace = "packages/coding-agent";

          # Skip native module rebuild for unneeded workspaces (e.g. canvas
          # from web-ui).
          npmRebuildFlags = [ "--ignore-scripts" ];

          nativeBuildInputs = [ makeBinaryWrapper ];

          # Build workspace dependencies in order, then the coding-agent.
          # We invoke tsgo directly for workspace deps to skip pi-ai's
          # generate-models script which requires network access; the model
          # catalog it would produce is supplied via modelData above.
          buildPhase = ''
            runHook preBuild

            npx tsgo -p packages/chord/tsconfig.build.json
            npx tsgo -p packages/tui/tsconfig.build.json
            npx tsgo -p packages/telemetry/tsconfig.build.json
            npx tsgo -p packages/ai/tsconfig.build.json
            npx tsgo -p packages/agent/tsconfig.build.json
            npx tsgo -p packages/protocol/tsconfig.build.json
            npx tsgo -p packages/client/tsconfig.build.json
            npx tsgo -p packages/server/tsconfig.build.json
            npm run build --workspace=packages/coding-agent

            runHook postBuild
          '';

          dontNpmPrune = true;

          preInstall = ''
            npm prune --omit=dev --no-save
          '';

          # npm workspace symlinks in the output point into packages/ which
          # doesn't exist there. Replace runtime deps with built content and
          # delete the rest.
          postInstall = ''
            local nm="$out/lib/node_modules/pi-monorepo/node_modules"

            # Replace workspace deps needed at runtime with real copies
            for ws in @earendil-works/chord:packages/chord \
                      @earendil-works/pi-ai:packages/ai \
                      @earendil-works/pi-agent-core:packages/agent \
                      @earendil-works/pi-client:packages/client \
                      @earendil-works/pi-protocol:packages/protocol \
                      @earendil-works/pi-telemetry:packages/telemetry \
                      @earendil-works/pi-tui:packages/tui; do
              IFS=: read -r pkg src <<< "$ws"
              rm "$nm/$pkg"
              cp -r "$src" "$nm/$pkg"
            done

            # Delete remaining workspace symlinks
            find "$nm" -type l -lname '*/packages/*' -delete

            # Clean up now-dangling .bin symlinks
            find "$nm/.bin" -xtype l -delete
          ''
          + lib.optionalString stdenvNoCC.hostPlatform.isDarwin ''
            # Remove foreign Linux binaries that make audit-tmpdir try to
            # inspect ELF RPATHs with patchelf
            rm -rf \
              "$nm/@anthropic-ai/sandbox-runtime/dist/vendor/seccomp" \
              "$nm/@anthropic-ai/sandbox-runtime/vendor/seccomp"
          '';

          postFixup = ''
            wrapProgram $out/bin/pi --prefix PATH : ${
              lib.makeBinPath [
                ripgrep
                fd
              ]
            } \
              --set-default PI_SKIP_VERSION_CHECK 1 \
              --set-default PI_TELEMETRY 0
          '';

          doInstallCheck = true;
          nativeInstallCheckInputs = [
            writableTmpDirAsHomeHook
            versionCheckHook
          ];
          versionCheckKeepEnvironment = [ "HOME" ];
          versionCheckProgram = "${placeholder "out"}/bin/pi";
          versionCheckProgramArg = "--version";

          meta = {
            description = "Coding agent CLI with read, bash, edit, write tools and session management";
            homepage = "https://pi.dev/";
            downloadPage = "https://www.npmjs.com/package/@earendil-works/pi-coding-agent";
            license = lib.licenses.mit;
            mainProgram = "pi";
          };
        });

      # pi's bundled ripgrep/fd are also on PATH for subagents at runtime.
      pi = pkgs.callPackage piPackage { };
    in
    {
      home.packages = [ pi ];
    };
}
